print(pcall(error, "error message"))
print(pcall(print, "print message"))